name: calibrate_model

dependencies:
  - python=3.8
  - numpy
  - matplotlib
  - pandas
  - pip:
    - torch==1.9.0
    - torchvision==0.10.0  -f https://download.pytorch.org/whl/torch_stable.html
    - opencv-python
